server:
  port: 8082

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      # The Global CORS Policy
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3001"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: Product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order, /api/order/**

# 🚨 FIX 1: Management moved to the root level with correct indentations
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name} 
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # 🚨 FIX 2: Explicitly forcing Eureka registration
    fetch-registry: true
    register-with-eureka: true